### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by JotaroKujo0525** [Tomato6966/Milrato-Discord-Bot#3]
![Screenshot_20210713-182206](https://user-images.githubusercontent.com/77835007/125436027-cb7a91fe-51b4-47e5-a8f9-c9a77c5e93b7.jpg)

**Comment by Frazix12** [comment]
i also have this error

**Comment by vanshit121** [comment]
me tooo

**Comment by Tomato6966** [comment]
Update your thricking nodejs version to v14.7

**READ THE `README.MD` FILE! I DONT GIVE SUPPORT FOR THIS REPOSITORY**
